import Head from "next/head";
import AllForms from "./../components/AllForms/AllForms";
import { ToastContainer } from "react-toastify";

// This is primary branch change

export default function Home() {
  return (
    <div>
      <Head>
        <title>Form Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AllForms />
        <ToastContainer />
      </main>
    </div>
  );
}
