import Head from "next/head";
import AllForms from "./../components/AllForms/AllForms";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Form Builder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AllForms />
      </main>
    </div>
  );
}
